include: package:flutter_lints/flutter.yaml
analyzer: 
  exclude:
    - "lib/generated_plugin_registrant.dart"
    - "**/*.g.dart"
    - "**/*.config.dart"
    - "**/*.mocks.dart"
linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_relative_imports: true
