name: museum_tour
description: A museum tour app
version: 0.1.0
code: 1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^1.7.5
  get_it: ^4.0.4
  injectable: ^1.0.2
  auto_route: ^0.6.6
  stacked_services: ^0.5.0
  path_provider: ^1.6.11
  hive: ^1.4.2
  hive_flutter: ^0.3.1
  url_launcher: ^5.5.0
  flutter_translate: ^1.6.0
  adobe_xd: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  auto_route_generator: ^0.6.6
  injectable_generator: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
