name: museum_tour
description: A museum tour app
version: 0.1.0
code: 1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  stacked: ^2.2.7
  get_it: ^7.2.0
  injectable: ^1.5.0
  auto_route: ^3.1.3
  path_provider: ^2.0.7
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  url_launcher: ^6.0.17
  flutter_translate: ^3.0.1
  flutter_feather_icons: ^2.0.0+1
  smooth_page_indicator: ^1.0.0+2
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  auto_route_generator: ^3.1.0
  injectable_generator: ^1.5.2
  mockito: ^5.0.16
  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.9.2
  json_serializable: ^6.1.1
  flutter_lints: ^1.0.4
  faker: ^2.0.0
  intl_utils: ^2.5.1

flutter_native_splash:
  image: assets/images/icon_foreground.png
  color: "F5CB5C"
  
flutter_icons:
  android: "ic_launcher" 
  adaptive_icon_foreground: "assets/images/icon_foreground.png"
  adaptive_icon_background: "#F5CB5C"
  ios: false
  image_path: "assets/images/icon_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand.ttf
        
flutter_intl:
  enabled: true
  main_locale: es
  arb_dir: lib/res/l10n
