name: Simple tests
on:
  push:
jobs:
  analyze-and-test:
    name: run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: configure enviroment
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - name: code analyze
        run: flutter analyze
      - name: unit tests
        run: flutter test
