name: Simple tests
on:
  push:
jobs:
  analyze-and-test:
    name: run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: configure enviroment
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - name: code analyze
        run: flutter analyze
      - name: unit tests 
        run: flutter test --coverage
      - name: Coverage tests (codecov)
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: ./coverage/lcov.info
